server:
  port: 8088

spring:
  application:
    name: API-GATEWAY

  # CORS (WebFlux)
  webflux:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
      allowed-headers: "*"
      allow-credentials: true

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: location-service
              uri: lb://LOCATION-SERVICE
              predicates:
                - Path=/api/locations/**
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
            - id: driver-service
              uri: lb://DRIVER-SERVICE
              predicates:
                - Path=/api/drivers/**
            - id: ride-service
              uri: lb://RIDE-SERVICE
              predicates:
                - Path=/api/rides/**
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/payments/**
            - id: rating-service
              uri: lb://RATING-SERVICE
              predicates:
                - Path=/api/ratings/**
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
      AUTH-SERVICE:
        connectTimeout: 3000
        readTimeout: 3000


logging:
  level:
    com.cabbooking.apigateway.client: DEBUG
    feign: DEBUG
