spring:
  application:
    name: DRIVER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/cab_booking_drivers?createDatabaseIfNotExist=true
    username: root
    password: cab_booking
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /api/drivers/v3/api-docs
  swagger-ui:
    path: /api/drivers/swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
