spring:
  application:
    name: PAYMENT-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/cab_booking_payment?createDatabaseIfNotExist=true
    username: root
    password: cab_booking
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
springdoc:
  api-docs:
    path: /api/drivers/v3/api-docs
  swagger-ui:
    path: /api/drivers/swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
